### ISSUE TITLE
Is there any way to get older torrents?

### ISSUE THREAD

**Issue by luchosaputo** [pacoesteban/Rarbg-torrentapi#5] opened 2018-03-31 20:48 UTC
Hey, i have been using the api recently and i cant get data for older torrents of a popular tv show for example, is there a way to do it?

**Comment by pacoesteban** [comment] 2018-03-31 22:29
Hi Lucho,

Please, try to be more specific. Show the errors you get (if any) or an example I can try to reproduce.
Anyway, your problem seems not to be related to this Perl module as far as I understand from your (not so descriptive) message, but to the API itself. So you should open the issue in the right place: https://github.com/rarbg/torrentapi

Cheers.

**Comment by luchosaputo** [comment] 2018-03-31 22:33
Oh, so sorry i thought you were handling the API as well, my bad. The link you wrote doesnt exist. Any way i can ask the owners of the API? Thank you so much

**Comment by pacoesteban** [comment] 2018-04-01 13:05
Sorry, the link I provided is valid, but seems to be private. I guess the API developers only allow access to module and apps devs. I don't have any other means of contact them.

I'll close this issue as it's not related to the Perl module.

**Closed as completed by pacoesteban** 2018-04-01 13:05 UTC
